

try {
    console.log(naoExiste)
} catch (error) {
    console.log(`A variavel n√£o existe!`)
    console.log(error)
};

